### ISSUE TITLE
Ninja All-Stars Data Files

### ISSUE THREAD

**Issue by MaxToreador** [BSData/bsdata#103]
I have data files for the newly released Ninja All-Stars game.

**Comment by amis92** [comment]
@MaxToreador are you willing to manage the repository? Do you want to be member? I've already sent you an invitation (right now). Please ask for any help, if you want to. https://github.com/BSData/ninja-all-stars

**Comment by MaxToreador** [comment]
I have a first release ready and someone helping me keep the files up to
date. It's not allowing me to upload though as I do not have push access.

*Southern New Rocks*
SouthernNewRocks.com

On Fri, Feb 12, 2016 at 7:14 AM, Amadeusz Sadowski <notifications@github.com

**Comment by amis92** [comment]
To have push access you need to accept the invitation in your email, or go to https://github.com/orgs/BSData

**Comment by MaxToreador** [comment]
Ok, missed that entirely at the top of the page. Files are uploaded.

*Southern New Rocks*
SouthernNewRocks.com

**Comment by amis92** [comment]
Ok, now please read through https://github.com/BSData/bsdata/wiki/Developer-Guide

Hint: points of interest:
* Most Common Mistakes
* Releasing
Cheers :)

**Comment by amis92** [comment]
I'm glad you've completed the release successfully :)
