### ISSUE TITLE
Download to iPad

### ISSUE THREAD

**Issue by DrDabbler** [BSData/bsdata#105]
I don't see how to download data files to the iPad app. The only option now that it is all in GitHub seems to be .zip download which doesn't find battlescribe as a possible destination.

What am I missing?

**Comment by amis92** [comment]
As an example I'll take 40k repo:
1. In README you have Overview section https://github.com/BSData/wh40k#warhammer-40000
2. Fourth bullet point gives you link to our data access site.
3. On that site you click on repo you want -  it'll download/opne index.bsi file which will be associated with BattleScribe.
4. Enjoy files (after a moment of patient waiting for download).

Cheers!
