### ISSUE TITLE
Spectre: operations

### ISSUE THREAD

**Issue by skimutis** [BSData/bsdata#106]
Hi. I'm really new to this kind of thing so please be patient. I would love to se the armylists of spectre: operations on battlescribe. Am I supposed to create this data file myself or how does it work. Do I need the rights of the game developer to do this?

Thanks for any guidence :)
/Martin

**Comment by Vescarea** [comment]
Hi, you can create your own data files for the game but have others contribute to it from this site. Do you have battlescribe installed on laptop or pc? there are 2 data editors in C:\Program Files (x86)\BattleScribe (may be different) and what you will find are;
- Game system editor 
- Catalogue editor
These 2 are how you can create your own data file check out http://www.battlescribe.net/help-overview.html for more info.
or https://www.reddit.com/r/BattleScribe

**Comment by skimutis** [comment]
Ah alright I get it (sort of). I have battlescribe on my android-phone right now but then I need to install it on my PC. Thanks a bunch!
