### ISSUE TITLE
Halo Ground Combat

### ISSUE THREAD

**Issue by KealL** [BSData/bsdata#108]
Hey Team

I know its still a few months off but lots of stat pics are up from Salute today and so I'd like to get started on this if people don't mind.

Can someone set it up and add me to it :)

Cheers

**Comment by amis92** [comment]
Is it something other, or is the name **Halo: Ground** **_Command_**?

**Comment by KealL** [comment]
sorry yes

Halo: Ground Command :)

**Comment by amis92** [comment]
There ya go :) https://github.com/BSData/halo-ground-command

**Comment by amis92** [comment]
You also should already have appropriate privileges, as it's now part of Spartan Games team you belong to.
