### ISSUE TITLE
New Games System - Dragon Rampant

### ISSUE THREAD

**Issue by Dogma2097** [BSData/bsdata#109]
As written - I've plowed through and made a serviceable Database for Dragon Rampant by Osprey Games.
I now need to share this bodge with the world!

**Comment by amis92** [comment]
Great! I'll send you invitation to our Osprey Games team - please accept it. Then you'll gain access to the repo I'll create for this game.

**Comment by amis92** [comment]
This is the new repo: https://github.com/BSData/dragon-rampant

After accepting the invitation you should be able to clone it and push changes.

Please take a look through Wiki, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide) which will definitely help you get up to speed with sharing datafiles. :)

Any more questions, please don't hesitate to ask here (even after I close the issue) or anywhere by mentioning me in a comment like so: `@amis92`.
