### ISSUE TITLE
HGC Test

### ISSUE THREAD

**Issue by KealL** [BSData/bsdata#110]
@amis92 Not sure if we have any policies so to speak so wondered if what I want to do is allowed so to speak:

Wanted to publish a test version of HGC (not yet as im not ready but soon) with a different layout for the two factions and then get feedback from the HGC FB community on which they prefer so I can implement that to both factions.

is that allowed?

**Comment by amis92** [comment]
Hmm I'm not sure I understand. Do you want to publish a game system where two factions have different layout and ask which layout does the community prefer? If so, go ahead.

However, if you asked whether you can publish two game systems with different layouts, then it a no - our app doesn't support more than one game system per repo.

I hope it helps. :)

**Comment by KealL** [comment]
Cheers, it was the first one, which the slight restatement that I am going to publish two layouts of the same faction (Alpha and Beta) as to provide a better comparison.

Thanks :)
