### ISSUE TITLE
Hello, i have new game files to be uploaded

### ISSUE THREAD

**Issue by Whotookallmynames** [BSData/bsdata#114]
Hello,

I have made a set of files for Galeforce 9's game Tanks, can they be added to the repository (http://battlescribedata.appspot.com/).

hxxps://www.dropbox.com/sh/u47ojh006ihm12c/AABRwdhL-a5UjdFpK27-qBD1a?dl=0

**Comment by amis92** [comment]
Hi @Whotookallmynames,

in general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Are you still interested? Should I send you an invite?

Amis

**Comment by Whotookallmynames** [comment]
Hi Amis,

Thanks, I have made a repository on my own account, I would be interested in getting the files hosted on your repository and site.

Regards,
Charles Shepherd

Sent from my iPhone

On 15 Jul 2016, at 22:10, Amadeusz Sadowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Whotookallmynames<https://github.com/Whotookallmynames>,

in general, if you want to provide new game system's files, the procedure is as follows:

  1.  I create new repository for given game system
  2.  I invite you to our organization
  3.  You accept the invitation and gain push/write access to this new repository
  4.  You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Are you still interested? Should I send you an invite?

Amis

-

**Comment by amis92** [comment]
Okay, so I've set the repo up: https://github.com/BSData/tanks You should get invitation by now. Accepting it will join you to the team that has access to this repo. Please check out https://github.com/BSData/bsdata/wiki/Developer-Guide, there are some good guidelines. :)

**Comment by Whotookallmynames** [comment]
Hello Amadeusz,


sorry to bother you but this is my first time using github.


I watch the video and tried to follow the instructions.


I made a clone of the /tanks repository in the desktop app, I then tried to add my files to it, when i clicked sync i got the error "Sync failed to push local changes" "it seems you do not have permission to push changes to this repository"


is there something i am doing wrong?


I also tried to make a new file on Github directly, this has opened a pull request but I'm unsure what to do from here on.


I think my problems ar that there are no existing files on the repository apart from the reademe file, where as your video tutorial is giving instructions on an already populated repository.


Regards,

Charles

________________________________

**Comment by amis92** [comment]
Hi,
whenever you need you can `@mention` me (ie. `@amis92`). It directly notifies me (by email) of the comment you post. Just something to keep in mind for future if I wasn't yet involved in the issue.

As per your problems, it was my fault, sorry. Forgot to set your team's permission to Write for this new repo.

All should work now. Readme is enough to make clone and you've succeeded with that, now that you've commited changes locally you should be able to push (sync) them. If not, make sure you're logged in with the same account.

And also just a friendly reminder, remember to save files in `.cat` and `.gst` instead of `.catz`/`.gstz` format (File->Save as...). My experience is that many people forget that on first time.

**Comment by Whotookallmynames** [comment]
Thanks,

I have synced the files and I have posted a release, just got to wait for the site to grab it and it should be all good.

Thanks for the help.

Regards,
Charles Shepherd

Sent from my iPhone

On 16 Jul 2016, at 23:05, Amadeusz Sadowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
whenever you need you can @mention me (ie. @amis92). It directly notifies me (by email) of the comment you post. Just something to keep in mind for future if I wasn't yet involved in the issue.

As per your problems, it was my fault, sorry. Forgot to set your team's permission to Write for this new repo.

All should work now. Readme is enough to make clone and you've succeeded with that, now that you've commited changes locally you should be able to push (sync) them. If not, make sure you're logged in with the same account.

And also just a friendly reminder, remember to save files in .cat and .gst instead of .catz/.gstz format (File->Save as...). My experience is that many people forget that on first time.

-

**Comment by amis92** [comment]
Looks good!
