### ISSUE TITLE
Age of Sigmar

### ISSUE THREAD

**Issue by Thumpy** [BSData/bsdata#115]
Hi

I have some files for upload, Age of Sigmar as well as a Orruks Battletome
http://tinyurl.com/zshz28o

**Comment by Thumpy** [comment]
And updated to be better. 
http://tinyurl.com/zshz28o

**Comment by amis92** [comment]
Please open issue in appropriate repo: https://github.com/BSData/warhammer-age-of-sigmar/issues/
