### ISSUE TITLE
Want to help adding profile information to WoodElves Units

### ISSUE THREAD

**Issue by Cupropituvanso** [BSData/bsdata#117]
Hello

I have downloaded your repository and thanks for your work.
For my use I want to fill it with profiles for units, weapons and anything necessary for the WoodElves Units. Normally I would do it in german and use only for myself, but I could do it on english and give it to you.

If this is interesting for you, please tell me if there is any update in work for the order catalog file.

Best Regards
Cupro

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case either [whfb](https://github.com/BSData/whfb), [WH:AoS](https://github.com/BSData/warhammer-age-of-sigmar) or [The 9th Age](https://github.com/BSData/The-9th-Age) (most probably WH:AoS).

I'll close this issue and respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
