### ISSUE TITLE
Konflikt 47 repository?

### ISSUE THREAD

**Issue by coruptcopy** [BSData/bsdata#119]
Is anyone planning on working on a Konflikt 47 repository? As it is basically a mod/add on to Bolt Action, I think we could easily start with those files and just add in the weird new units and special rules. If someone is working on it, you are the best! :-D

**Comment by amis92** [comment]
Seems there are not many volunteers. If you want to, please tell me; I can arrange a new repository for this game system if required (and you'd contribute).

**Comment by coruptcopy** [comment]
I will not have time until Thanksgiving to get to work in this, but I am willing to start work in it then. Thanks!

**Comment by amis92** [comment]
Hi @coruptcopy ,

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system (https://github.com/BSData/konflikt47)
2. You upload files and maintain them if possible.

You're already member of BSData, so I've simply added you to the team for Warlord Games. You should have write access right now.
