### ISSUE TITLE
Design Mockup + Introduction

### ISSUE THREAD

**Issue by jacksonhyde** [BSData/bsdata#12]
Hi guys - looks like I'll be doing some design work for this awesome project! This is me if you're interested - http://uk.linkedin.com/pub/jackson-hyde/10/570/164/

Not sure if Jon's had the chance to share this with you guys yet, a very early mockup I knocked up on a lunchbreak. Very WIP and I imagine there's more functionality that will need fleshing out.

![bsdata mockup](https://f.cloud.github.com/assets/1104467/2277104/fad465e2-9f3b-11e3-8ce9-31c6ee6f674c.png)

A couple of talking points:

* The image I've used for the bg represents functionality allowing the administrator to upload their own image to use as a bg - do you think this functionality is deliverable?
* Logo is most definitely a placeholder! I was thinking a battle damaged ammo crate might work nicely for the final thing.

Any thoughts/issues with what I've done so far? Don't be shy, I'm not a diva :)

**Comment by Jonskichov** [comment]
This is OLD so I'm closing.

@jacksonhyde If you ever fancy getting involved, feel free to open an issue or contact one of us.
