### ISSUE TITLE
New repo for Dust 1947?

### ISSUE THREAD

**Issue by frankysan** [BSData/bsdata#120]
I've been working on the data files for the new version of Dust tactics called Dust 1947. However, as the game has changed name, and there were a lot of changes necessary to the data files, I think it would make the most sense to move my new files to a new repo, called Dust 1947 (dust1947 for short). Thoughts?

My files are currently at https://github.com/frankysan/dust1947

**Comment by amis92** [comment]
I guess that's a good idea. Do you suggest also that the old Dust Tactics be delisted?

**Comment by frankysan** [comment]
Maybe. I'm sure some people who want to stick with the older stuff might get upset though.

**Comment by amis92** [comment]
There it goes: https://github.com/BSData/dust1947

I won't remove the old repo.
