### ISSUE TITLE
Ronin Repository

### ISSUE THREAD

**Issue by Ayaxsfs** [BSData/bsdata#124]
Edit: found the getting starter thread :P

**Comment by amis92** [comment]
After a quick search I was unable to find any miniature game. What is this issue for? Do we have that already, or do you want to start something?

**Comment by Ayaxsfs** [comment]
i want to start a reposiroty for Ronin, an Osprey game.

https://ospreypublishing.com/ronin-skirmish-wargames-in-the-age-of-the-samurai

**Comment by amis92** [comment]
Hi @Ayaxsfs ,

in general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Also please remember to take a good read through [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Amis
