### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by DonMorr** [BSData/bsdata#125]
Hi There,
I would like to join the repo so I can help improve the horus heresy data files.
Cheers,
Donal

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [Horus Heresy](https://github.com/BSData/horus-heresy).

I'll close this issue and respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
