### ISSUE TITLE
[Add New Game System Request] Knight Models games

### ISSUE THREAD

**Issue by nexomad** [BSData/bsdata#130]
Hello!

My name is Adrian Fuertes, and I want to ask if it's possible to add to your repositories 2 new game Systems for the games Batman Miniature Game and Super Hero Miniature Game of the miniature company Knight Models.

I have already created both systems, complete and updated for Super Hero Miniature Game and a 70% more or less of the miniatures for Batman Miniature Game. 

Actually you can find these repositories in the blog that I am collaborating, **La Biblioteca de Alfred**:
[http://bit.ly/2hDC8AV](url)
[http://bit.ly/2gSQX56](url)

I know that this is not the place to contact you, but I don't know where to contact :)

Kind regards!

**Comment by amis92** [comment]
That is exactly the place :D

Would `Batman`(`batman` repo) and `Super Hero` (super-hero` repo) be adequate names, or is Miniature Game suffix important?

**Comment by nexomad** [comment]
Hi!


The suffix 'Miiature Game' is important in both, yes.


Would you host the data? Because now I have all the data on a public folder of Dropbox, but the Public folders will be closed on March [☹]


________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: lunes, 19 de diciembre de 2016 18:30:20
Para: BSData/bsdata
Cc: nexomad; Author
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)


That is exactly the place :D

Would Batman(batman repo) and Super Hero (super-hero` repo) be adequate names, or is Miniature Game suffix important?

**Comment by amis92** [comment]
Hi @nexomad,

Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system (https://github.com/BSData/batman and https://github.com/BSData/super-hero-universe)
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

**Please read carefully**:
As this is a new repository, please read Developer Guide linked above very carefully. Most important: save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Also you may join our Wh40k team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) - it's very active and you can ask for some datafile-oriented help if needed.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

**Comment by nexomad** [comment]
Sorry about my delay to upload the files, I didn't have time to do this.


I hope I'll upload the files in the next weeks, and also with all the Batman Miniature Game data done.


Thanks for you patience and help.


Regards.

________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: martes, 3 de enero de 2017 12:37:04
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)


Hi @nexomad<https://github.com/nexomad>,

Please accept the invitation in the email or on the BSData organization webpage<https://github.com/BSData>. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:

  1.  I create new repository for given game system (https://github.com/BSData/batman and https://github.com/BSData/super-hero-universe)
  2.  I invite you to our organization
  3.  You accept the invitation and gain push/write access to this new repository
  4.  You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through Wiki pages<https://github.com/BSData/bsdata/wiki>, there are some useful guides, especially Developer Guide<https://github.com/BSData/bsdata/wiki/Developer-Guide>.

Please read carefully:
As this is a new repository, please read Developer Guide linked above very carefully. Most important: save all files in unzipped format (.cat instead of .catz and .gst instead of .gstz); you can achieve this using File->Save as and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (index.xml or index.bsi), the website on AppSpot does indexing automatically.

Also you may join our Wh40k team in Gitter chat room (GitHub login): [Join the chat at https://gitter.im/BSData/wh40k] <https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge>  - it's very active and you can ask for some datafile-oriented help if needed.

Cheers!
Amis

PS You can always @mention me by writing @amis92 in your issue comment, and I'll try to help you out.

**Comment by nexomad** [comment]
Hello.


I am the responsible of the Super Hero Miniature Game System, I kept aside the project due a bug that didn't allow me to hide a character if another with same name exist; now this bug is solved, so I wanted to come back to work! 😊


I wanted to change the name of the actual Game System (Super Hero Miniature Game) to DC Universe Miniature Game (the real name of the game) and, if it is possible, move apart the extinct Marvel Universe Miniature Game in other Game System. The reason is that in Super Hero Miniature Game I mixed both games, but this name is not real and is less visible to people, apart from that Marvel's System is not going to have any new character.


Is possible to do this?


Thanks for your time!


Regards.

**Comment by amis92** [comment]
So, you'd like to rename and update Super Hero to DS Universe, and create a separate new one for Marvel?

What experience do you expect users of current repo to have? Will they know to subscribe to a new repo? Will they want to update to one of them?

**Comment by nexomad** [comment]
Yes, it would be:


- Change the Game System name from Super Hero Universe Miniature Game to DC Universe Miniature Game, maintaining the same Unique ID (I will test if it will automatically update, it should has).


- Create a new Game System called Marvel Universe Miniature Game and move all the specific data of Marvel.


- If not, we simply can change the name from Super Hero Universe Miniature Game to DC Universe Miniature Game, and inside include the Teams for Marvel (as actually is). (Maybe this is the best option).


I have a blog (http://labibliotecadealfred.blogspot.com.es/) where I inform this kind of news and step-by-step guides to update the data.

La Biblioteca de Alfred<http://labibliotecadealfred.blogspot.com.es/>
labibliotecadealfred.blogspot.com.es
Acabando de terminar la resaca navideña, y mientras nos vamos mentalizando con empezar con la operación bikini, vamos a analizar las novedades de enero que ya va ...



________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: jueves, 25 de enero de 2018 9:40
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)


So, you'd like to rename and update Super Hero to DS Universe, and create a separate new one for Marvel?

What experience do you expect users of current repo to have? Will they know to subscribe to a new repo? Will they want to update to one of them?

**Comment by amis92** [comment]
It's not only a problem with unique ID. If we change repo name, we will break updates for existing users. They'll need to add these new repositories. If that's not a problem, then we're good.

Not sure if including Teams for Marvel under DC Universe is good xD

**Comment by nexomad** [comment]
Yes, I know what you mean. Don't worry, any new user will see DC and Marvel games, and the rest will be informed via the blog.


So, we make this changes:


- Change the Game System name from Super Hero Universe Miniature Game to DC Universe Miniature Game.


- Create a new Game System called Marvel Universe Miniature Game and move all the specific data of Marvel.


How long would it take to make the changes? I'm just saying this for setting a changeover date and preparing my part too.


Thanks a lot!

________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: jueves, 25 de enero de 2018 12:40
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)


It's not only a problem with unique ID. If we change repo name, we will break updates for existing users. They'll need to add these new repositories. If that's not a problem, then we're good.

Not sure if including Teams for Marvel under DC Universe is good xD

**Comment by amis92** [comment]
Actually, I can do that right now. I think a better approach will be to create two new repositories, where you'll just upload files and make a release whenever convenient for you. The Super Hero repo will be archived. What about that?

**Comment by nexomad** [comment]
Ok! I like that idea 😊


________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: jueves, 25 de enero de 2018 15:54
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)


Actually, I can do that right now. I think a better approach will be to create two new repositories, where you'll just upload files and make a release whenever convenient for you. The Super Hero repo will be archived. What about that?

**Comment by amis92** [comment]
There you go:
* https://github.com/BSData/dc-universe
* https://github.com/BSData/marvel-universe

You're already a member so I've simply assigned you permissions. You can proceed as you wish in terms of dates.

Let me know after the change, so I we can retire the super-hero repo.

**Comment by nexomad** [comment]
Hello.


After a few but heavy changes, I am ready to:

- Delete the Super Hero Universe Miniature Game Repository

- Release Marvel Universe Miniature Game.

- Release DC Universe Miniature Game.


About this last point, I'm not sure if is going to be the same Unique ID System of Super Hero changed to DC. I mean:


Unique Systems ID :

Marvel Universe Miniature Game
c372-4887-df6a-ad9e

DC Universe Miniature Game
a8b386b1-4fa1-5d7e-20fe-68d346fa8983

Super Hero Universe Miniature Game
a8b386b1-4fa1-5d7e-20fe-68d346fa8983


I mean, the ID of the Super Hero and DC is the same on purpose, to upload the actual game (DC).


Do you understand my weird explanation? 😊


Regards.

________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: viernes, 26 de enero de 2018 0:03
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)


There you go:

  *   https://github.com/BSData/dc-universe
[https://avatars2.githubusercontent.com/u/6423416?s=400&v=4]<https://github.com/BSData/dc-universe>

GitHub - BSData/dc-universe: DC Universe Miniature Game<https://github.com/BSData/dc-universe>
github.com
Join GitHub today. GitHub is home to over 20 million developers working together to host and review code, manage projects, and build software together.

  *   https://github.com/BSData/marvel-universe
[https://avatars2.githubusercontent.com/u/6423416?s=400&v=4]<https://github.com/BSData/marvel-universe>

GitHub - BSData/marvel-universe: Marvel Universe Miniature ...<https://github.com/BSData/marvel-universe>
github.com
Join GitHub today. GitHub is home to over 20 million developers working together to host and review code, manage projects, and build software together.


You're already a member so I've simply assigned you permissions. You can proceed as you wish in terms of dates.

Let me know after the change, so I we can retire the super-hero repo.

**Comment by amis92** [comment]
Yeah! That's ok. Proceed with releasing. I'll archive the Super Hero repo.

**Comment by nexomad** [comment]
Hello.


I recently released  DC Universe Miniature Game. Few days ago I released too the Marvel one, but I saw a few mistakes and today I uploaded another release with changes, naming it 1.1. The problem is... Is this the way to update data? Making a new release with the Release option, creating a new version? Of course I upgraded the version on the modified catalogues, but I'm not sure if this is the way to update the general Game System; now is not updating.

________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: lunes, 12 de febrero de 2018 20:49
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)


Yeah! That's ok. Proceed with releasing. I'll archive the Super Hero repo.

**Comment by amis92** [comment]
What you described sounds okay. AppSpot website (and by extension, updating from BattleScribe) use cache, which is updated only so often. You may need to wait up to a day.

**Comment by nexomad** [comment]
Ok, great! So Super Hero Universe will be changed to DC Universe, no? I mean: If somebody had the repository of Super Hero Universe, now will be automatically changed to DC Universe, is it like this?


________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: miércoles, 14 de febrero de 2018 17:06
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)


What you described sounds okay. AppSpot website (and by extension, updating from BattleScribe) use cache, which is updated only so often. You may need to wait up to a day.

**Comment by amis92** [comment]
No, that's not going to happen. People will need to change their Manage Data links

---
Amadeusz Sadowski

________________________________

**Comment by nexomad** [comment]
Ok, perfect. Thanks!


________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: miércoles, 14 de febrero de 2018 18:44
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)

No, that's not going to happen. People will need to change their Manage Data links

---
Amadeusz Sadowski

________________________________

**Comment by nexomad** [comment]
Ok, both repositories are uploaded, including the new version of Marvel 😊. Please, could you delete the Super Hero Universe Miniature Game repository?

Thanks!


________________________________
De: Amadeusz Sadowski <notifications@github.com>
Enviado: miércoles, 14 de febrero de 2018 18:44
Para: BSData/bsdata
Cc: nexomad; Mention
Asunto: Re: [BSData/bsdata] [Add New Game System Request] Knight Models games (#130)

No, that's not going to happen. People will need to change their Manage Data links

---
Amadeusz Sadowski

________________________________

**Comment by amis92** [comment]
I can archive it. Deletion is not a thing (by that I mean we don't delete repos by design).

**Comment by nexomad** [comment]
The problem now is that, as the DC and Super Hero have the same Unique ID
System, they are mixing in app... Maybe is better to change the unique ID
on the DC System?

2018-02-15 11:41 GMT+01:00 Amadeusz Sadowski <notifications@github.com>:

**Comment by amis92** [comment]
@nexomad you need to be more specific as to what mixes with what. Users who want to use new repos need to Purge Data in their BattleScribe apps and remove the link to SuperHeroes in Update Data, simple as that.

There's not really any other way to retain old rosters, and I think it's too late to change gamesystemId of DC gst.

**Comment by nexomad** [comment]
Yes, the problem is that I thought that we are able to replace the Super
Hero to DC. Don't worry, in my blog I'll publish a guide to purge all the
data and delete the old repository.
And sorry about the inconvenience, I'm new in this stuff :)
Thanks!

2018-02-15 15:43 GMT+01:00 Amadeusz Sadowski <notifications@github.com>:

**Comment by amis92** [comment]
Cool. I think I also misunderstood you on the gst id  convergence. Sorry!

**Comment by nexomad** [comment]
Hello.

I write directly to you here because I have your contact when we talked
about other Game System:

I received no answer in the issue *#212 [Add new Game System request] Harry
Potter Miniatures Adventure Game*, and I wanted to know if that's the
correct place to write my petition. Of course I don't want to pressure you,
I only want to ask :)

Regards!

>

**Comment by amis92** [comment]
No, not really the correct place. I'll move the issue over to catalogue-development.

**Comment by nexomad** [comment]
Ok, thanks! I followed the link on the main site of Battlescribe Data Files
<http://battlescribedata.appspot.com/> (exactly this link
<https://github.com/BSData/bsdata/issues>), I think it is wrong.

So now I have to wait until any of you craete the repository, no?

Thanks!

**Comment by amis92** [comment]
Oh! That's true. I'll note to modify this :)

**Comment by nexomad** [comment]
You're welcome! One little question: I uploaded and released all necessary
files and I can't see them in Battlescribe Data, do I have to wait until
the automatism publish the GameSystem or I did something wrong?

Regards.

**Comment by amis92** [comment]
You do have to wait, same as with update releases. :)

**Comment by nexomad** [comment]
Ok, thanks; I've never understood the procedure :D

**Comment by nexomad** [comment]
Other quick question: If I want to upload the same Harry Potter Game System
but, instead in english, in spanish, do we have to create another
repository?

**Comment by amis92** [comment]
The discussion about Harry Potter system should be in appropriate Issue. This issue is for Knight Models.

Last answer re: Harry Potter here.

Localization in catalogues is not yet supported and won't be in near future: https://github.com/BSData/catalogue-development/issues/15
