### ISSUE TITLE
Blood Angels  Baal Strike force error 

### ISSUE THREAD

**Issue by IIIXprototype** [BSData/bsdata#133]
For some reason its not giving the rules red thirst for the baal strike force

![capture44444](https://cloud.githubusercontent.com/assets/25163233/22004000/f7e75fc2-dc25-11e6-869f-46b62a506726.PNG)

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [wh40k](https://github.com/BSData/wh40k).

I'll close this issue and respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
