### ISSUE TITLE
Appspot - error getting data files

### ISSUE THREAD

**Issue by zopha** [BSData/bsdata#138]
There seems to be a general issue on Appspot where it's just returning this message

![2017-02-20 12_43_28-battlescribe data files](https://cloud.githubusercontent.com/assets/1666415/23125598/71d6c598-f76a-11e6-9e5f-ca41e38347a6.png)

I've seen it come up for a few hours but then just presents this error for most of the day again.

Not sure if it's a coincidence but this started happening after a .gstz file was accidently included in a  Heresy release. It was removed shortly after an another release was tagged and appspot seemed to go back to normal for awhile.

**Comment by ChapterGrim** [comment]
This is also relayed to the latest Battle Scribe...
It refuses to update at all...

**Comment by IdleMuse** [comment]
Battlescribe will be looking at the repo URLs, which are all under http://battlescribedata.appspot.com/repos/ (currently down) hence the problem updating, and presumably tied to the problem indexing them for the UI frontend too.

**Comment by zopha** [comment]
It happened again this morning, just before it went down all the catalogue links where duplicated, I've attached an example.

![2017-02-22 11_31_57-](https://cloud.githubusercontent.com/assets/1666415/23213219/fb26349e-f901-11e6-965a-0a5b06c1616f.png)

**Comment by IdleMuse** [comment]
Seems to be back up now?

**Comment by zopha** [comment]
Yeap. It's up for me.
