### ISSUE TITLE
Land Raider Ares

### ISSUE THREAD

**Issue by lhavoc1** [BSData/bsdata#139]
Can you add the Land Raider Ares and Land Raider Achilles to the Warhammer 40,000 rosters as an option?

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [wh40k](https://github.com/BSData/wh40k).

I'll close this issue now. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
