### ISSUE TITLE
The 9th Age Spanish files - additional catalogue

### ISSUE THREAD

**Issue by Arturius1** [BSData/bsdata#142]
Hello @amis92 

In the 9th Age we have a rather big Spanish community and they would like to ask if it's possible to add another, separate, catalogue to appspot repository with Spanish language datafiles?

Is it possible, and how it can be done?

Best regards
Arturius

**Comment by amis92** [comment]
I don't really have time right now, but I'll come back with an answer eventually, that's why I've assigned it to myself.

**Comment by Arturius1** [comment]
Thank you, it's no longer needed.

**Comment by amis92** [comment]
Reference: https://github.com/BSData/catalogue-development/issues/15
