### ISSUE TITLE
Tau army war hammer 40k

### ISSUE THREAD

**Issue by rookiemaisey** [BSData/bsdata#145]
I can't find the data pack for the coalition command. Can I have either a link to the data pack, or instructions on how to find it please.

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [wh40k](https://github.com/BSData/wh40k).

I'll close this issue and someone will respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
