### ISSUE TITLE
No 'evil' armies

### ISSUE THREAD

**Issue by hirwain** [BSData/bsdata#146]
There doesn't seem to be any bad armies for the Hobbit, particularly Mordor and umbar

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [hobbit](https://github.com/bsdata/hobbit).

I'll close this issue and respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.

**Comment by hirwain** [comment]
Hi,

I opened this issue in the hobbit section 11 days ago but have had no reply. I'm new to github so I'm not sure I've done it right. Cano you help please?

Martin
________________________________

**Comment by amis92** [comment]
Well, I don’t maintain Hobbit repo and so I won't be able to help you. It seems that there are no active maintainers there, then. Not much I can do for you, unfortunately. You might want to “bump” the issue, but until someone responds it's all you can do really. :/

Sent from my Windows 10 phone
