### ISSUE TITLE
Warzone Resurrection

### ISSUE THREAD

**Issue by Alakhai2001** [BSData/bsdata#148]
I am the creator of the Warzone Resurrection 1.X file.
Currently I am maintaining the BS file for the 2.0 version of the game.
How I can appear in the list of supported games inside BattleScribe? Currently I simply share the .bsr file hosted in my personal web.

**Comment by amis92** [comment]
Hi @Alakhai2001 ,

in general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So  you'll have to do some work to make our website host those files.

Are you still interested? Should I send you an invite?

Amis
