### ISSUE TITLE
Request to join for Walking Dead

### ISSUE THREAD

**Issue by skyengel** [BSData/bsdata#150]
Hi,
i want to help to update the Walking Dead All out War File.

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, as described in https://github.com/BSData/bsdata/wiki/Joining-Repository

I'll close this issue and respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
