### ISSUE TITLE
appspot update

### ISSUE THREAD

**Issue by Zappline** [BSData/bsdata#154]
I was just wondering how long it usually take for a publication on GitHub to be updated to the appspot repo section. I also would like to know if it matters if I tick the pre-release box before publication? Wanted to first try out a simple little update before i went ahead to update all the bigger changes I have done in case of any errors showing up (a lot easier to fix a small change then a big one).

**Comment by amis92** [comment]
1. Up to 12 hours I think
2. Pre-release doesn't change a thing.

**Comment by Zappline** [comment]
Ah I see. Would you prefer I make all the updates now in one go or should i wait until the first update goes through just to make sure it all works at it should? (New at all this as you know :) )

**Comment by amis92** [comment]
Depends on you, I won't be using Blood Bowl :D

Update whenever you have spare time. Releasing more often than once per day is not bad, it's just mostly useless. Also, if it works for you locally, there should be no problem for AppSpot.

**Comment by Zappline** [comment]
Ah I see. Then I'll update everything now it should be working fine I think. Thanks for the help.
