### ISSUE TITLE
Fantasy Battles: The 9th Age missing??

### ISSUE THREAD

**Issue by Karanadon** [BSData/bsdata#158]
Hey,
I help maintain the 9th Age files and it seems the link to them has disappeared from the hosting page?

**Comment by amis92** [comment]
http://battlescribedata.appspot.com/#/repo/The-9th-Age works for me?

**Comment by Karanadon** [comment]
Oh strange, it's back now. It has disappeared before for some reason. Will get a screenshot if it happens again.
