### ISSUE TITLE
New Repo for Star Wars: Legion

### ISSUE THREAD

**Issue by XWingDrLucky** [BSData/bsdata#159]
I put together a repo for Fantasy Flight's upcoming Star Wars ground combat game, Star Wars: Legion.  The game isn't released yet but based on GenCon demos and the cards spoiled so far (which is nearly the whole core set), I've got a functioning repo (even if there are a few details that will likely change when the official release happens).

I'm already a maintainer in the Data Authors group for Star Wars games so I don't need any new permissions or anything.  I just need to get the repo up.  I'll maintain it.

**Comment by amis92** [comment]
I see you've come prepared like a pro. 🥇 

What you requested have here is: https://github.com/BSData/star-wars-legion
