### ISSUE TITLE
App data update schedule

### ISSUE THREAD

**Issue by M-J-Hastings** [BSData/bsdata#162]
I have added new catalogues and fixed several issues in the Hobbit data. I pushed to the master and made a new release with a new version, at 10 pm  (gmt) on the 18th.  25 hours later and the app data still does not update to this latest version. 

How regularly does the app data update?

**Comment by amis92** [comment]
It sure seems like it's available https://twitter.com/BSData/status/910098411830906880

But if you're talking about the app itself, BattleScribe checks for data updates only once per week. If you want to enforce data update, go to Manage Data and select Update.
