### ISSUE TITLE
Age of Sigmar General's Handbook 2017

### ISSUE THREAD

**Issue by Horotius** [BSData/bsdata#163]
Hey there, I was wondering if the AoS file could be updated to the new point costs of everything from the generals handbook 2017. I also noticed that a new army (Kharadron Overlords) is not within the order list as well.

Also if there was anyway to add the new command traits/artifacts for the factions that would be cool as well (due to some got new allegiance abilities, command traits, and artifacts.

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [Age of Sigmar](https://github.com/BSData/warhammer-age-of-sigmar).

I'll close this issue and someone more appropriate should respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
