### ISSUE TITLE
Warhammer 40k is missing

### ISSUE THREAD

**Issue by dragongame** [BSData/bsdata#165]
Wh40k is missing on AppSpot

**Comment by rmld** [comment]
It's at the github site, but there's no index.bsi to download to transfer it to Battle Scribe.

**Comment by rmld** [comment]
![image](https://user-images.githubusercontent.com/17058946/32358478-cf7641bc-c01c-11e7-95e3-1fb91a2be3d3.png)

**Comment by oarmisaelo** [comment]
So we can’t use it in mobile app anymore?

**Comment by amis92** [comment]
Please see: **https://github.com/BSData/wh40k/issues/1706**
