### ISSUE TITLE
Point values for Craftworld army

### ISSUE THREAD

**Issue by rmld** [BSData/bsdata#167]
@FarseerVeraenthis Great work on the rules! I noticed some point discrepancies, though:

Banshee Exarch with Execusioner and Pistol should be 16 points total (9 for Banshee, 7 for Executioner, 0 for pistol)

Scorpion Exarch with Scorpion Chainsword and Scorpion Claw should be 26 points total (13 for Scorpion, 1 for Chainsword, 12 for Claw)

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [wh40k](https://github.com/BSData/wh40k/issues/).

I'll close this issue and appropriate person will respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
