### ISSUE TITLE
Hobbit SBG BS Repositories Using Backups Instead of New Versions

### ISSUE THREAD

**Issue by M-J-Hastings** [BSData/bsdata#168]
When I do a fresh download of the Hobbit SBG data repository, it uses the wrong versions of the catalogs that I have recently edited.

I have worked on Eregion & Rivendell, which  is now on V.13, and Rohan, which  is now on V.7. This data is all online (2.3.13-beta) and a fresh clone to the GitHub desktop app. retrieves these versions and the edits are all there in the Data Editor app. 

In the roster app., a fresh repository download doesn't have these version, instead it contains the backup versions (V.3 for both) of these catalogs for no apparent reason.

How do I make it use the correct catalogs?!

Kindly,

Matthew H.

**Comment by capitaladot** [comment]
Have you created pull request for your changes? You should if you haven't.

**Comment by amis92** [comment]
The issue seems pretty outdated. Closing.
