### ISSUE TITLE
Infinity N3

### ISSUE THREAD

**Issue by MrNailbrain** [BSData/bsdata#169]
Hey all, I’m working on a data file for Infinity and I’ve got one full faction done. Progress is a little slow but I’ve got a good system set up for stats entry.

There aren’t many list creators for Infinity out there -Corvus Belli has an official list builder app on Android and a mobile site, but noting yet for iPhones. 

The big thing I’m trying to do is make the rules text linkable to the wiki - is there a good way to embed hyperlinks in Rule objects? 

Otherwise I’m quite pleased with the data file editor interface and I’m hoping to have something up pretty soon.

**Comment by Ayaxsfs** [comment]
This will be pretty handy to the iPhone users.

**Comment by MrNailbrain** [comment]
I've finished the first faction (PanOceania) and I uploaded to a github repository to test it on mobile.  How do I get the files to the main BSData repository?

**Comment by Ayaxsfs** [comment]
You must ask for a new repository to be created, then upload the files using the github app.

Ask for a new repository like this

https://github.com/BSData/bsdata/issues/157

**Comment by amis92** [comment]
Closed by #170
