### ISSUE TITLE
Osprey's Fighting Sail Repository.

### ISSUE THREAD

**Issue by Dr-Csernus** [BSData/bsdata#171]
Hello. I wrote a repository for Osprey's Fighting Sail system and would like to publish it.

**Comment by Dr-Csernus** [comment]
P.S. I wrote and published the War of the Ring repository, so I can manage everything if you make the repository available for me.

**Comment by amis92** [comment]
Hi @Dr-Csernus,

The repo's here: https://github.com/BSData/fighting-sail

Cheers!
Amis
