### ISSUE TITLE
Request to join BSData Project (Wh40k)

### ISSUE THREAD

**Issue by ibankzero** [BSData/bsdata#176]
I want to help improve data in Wh40k

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [wh40k](https://github.com/BSData/wh40k/issues/new?title=%5BJoin%20Request%5D).

I'll close this issue and someone will respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.
