### ISSUE TITLE
New repo - Forager

### ISSUE THREAD

**Issue by mugginns** [BSData/bsdata#179]
Hi,

I've written a game system and catalogs for [Forager](https://www.kickstarter.com/projects/1718486616/forager-tabletop-napoleonic-skirmish-game-stand-to). Can you open a repo please

Michael

**Comment by amis92** [comment]
Invitation: https://github.com/BSData/forager/invitations

Repo: https://github.com/BSData/forager

Cheers!

**Comment by mugginns** [comment]
Hi, unfortunately the invitation didn't work for me - it says Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

**Comment by amis92** [comment]
Oh sh*t you're right, I've invited **muggins** with single *n* xD Fixing mistake right now...

**Comment by mugginns** [comment]
Hi, sorry to be a bother - I've uploaded my files as CAT etc, and done a release, but it is not showing up on the http://battlescribedata.appspot.com/#/repos site. Did I do something wrong? Sorry for the troubles.

Thanks

**Comment by amis92** [comment]
Works now, it's just taking it's time (6-12hrs sometimes), the sync mechanism is a polling one, and not very often too.

http://battlescribedata.appspot.com/#/repo/forager
