### ISSUE TITLE
Problem with naming .gst

### ISSUE THREAD

**Issue by DarthFraggle** [BSData/bsdata#182]
I think I made an error in naming my .gst file "Warzone Resurrection 2.2". Now that 2.3 is out, if I were to change the name would it invalidate all lists made with the previous version? I'm considering renaming it Warzone: Resurrection in order to future-proof it. Right now the number of people using it is small enough that it may be the time to do it, regardless. Advice? @amis92

**Comment by amis92** [comment]
https://github.com/BSData/bsdata/wiki/Developer-Guide#most-common-mistakes

You can freely rename the inside-name of game system if you desire. The filename is only visible to you - end users almost never see files; you can rename file, but as you said that will "break" all previous rosters and what's more, it'll create conflict with current files users have, as the game system Id didn't change. So after renaming the file, users will have to purge the data and re-download them.

I suggest leaving filename as it is, and just changing the display name in the game system file.

**Comment by DarthFraggle** [comment]
Thank you very much, I was hoping there was a better solution. It worked and I'll close this down.
