### ISSUE TITLE
Upload Underhive to bsdata repository available within mobile and desktop apps?

### ISSUE THREAD

**Issue by pinecones** [BSData/bsdata#183]
Upload Underhive to bsdata repository available within mobile and desktop apps?

I am not sure how to do this myself. The underhive hasn't had issues and has been reviewed. Plus getting it out to more people would find any other errors.

BSdata/necromunda-underhive

**Comment by amis92** [comment]
I've linked you to the [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide) when giving you the primer in #172. Please read carefully, you may find **Releasing** section quite interesting :)
