### ISSUE TITLE
40k V8 / points for the Twin Boltgun on Biker

### ISSUE THREAD

**Issue by PogoNeo** [BSData/bsdata#187]
Hi,

For this data "Warhammer 40,000: Heralds of Ruin 8th Edition", I don't see the value of the Twin Boltgun for the Space Marine (4pts/model).

Best Regards, 
PogoNeo

**Comment by PogoNeo** [comment]
Sorry, the good value is 2pts/model for the Twin Boltgun

**Comment by amis92** [comment]
Hello,

this is game-system specific issue. I'd like to kindly ask you to open the issue in the appropriate repo, in this case probably [HoRKT 40k](https://github.com/BSData/wh40k-heralds-of-ruin-killteam).

I'll close this issue and hopefully an appropriate maintainer will respond to the new one when you open it. I suggest you copy the text all over.

Kind regards,
Amis, your local admin :)

PS you may also `@mention` me to quickly take my attention.

**Comment by PogoNeo** [comment]
Thanks for your help, and sorry for the wrong location. 

I go to the good chanel with this point ;) 


Best Regards, 
PogoNeo
