### ISSUE TITLE
New repository: AVP: Unleashed

### ISSUE THREAD

**Issue by DarthFraggle** [BSData/bsdata#189]
Hello, I've just finished the files for AVP: Unleashed by Prodos games. Could we start a repository for them?

**Comment by DarthFraggle** [comment]
@amis92 is the procedure the same for starting a second repository? I haven't uploaded the files yet as last time I had to re-upload them to the repository you created.

**Comment by amis92** [comment]
Yeah, procedure is the same. I'll create the repo.

**Comment by amis92** [comment]
https://github.com/BSData/avp-unleashed/invitations

Cheers!
