### ISSUE TITLE
URL https://battlescribedata.appspot.com/repos seems to be down

### ISSUE THREAD

**Issue by madlou** [BSData/bsdata#190]
I'm getting the below error on https://battlescribedata.appspot.com/repos:

Title: 500 Server Error

Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.

**Comment by D6Frag** [comment]
Same for me - java.io.IOException: Server returned HTTP response code: 500 for URL: https://battlescribedata.appspot.com/repos

**Comment by madlou** [comment]
Seems to be fine for me now, closing.
