### ISSUE TITLE
Deathwatch

### ISSUE THREAD

**Issue by don124** [BSData/bsdata#191]
Hi guys I was just wondering if possible would someone be able to add to the deathwatch kill team data file an individual primaris marine as I want to use 1 of each but pay all the points for a squad of 3 or 5 or will an individual primaris be added when the kill team game is released if I knew how to do it myself I would but as I don't I need help with the issue or if someone can give me help I will more than happily do it myself

**Comment by amis92** [comment]
Hi. I'm sorry, but the lack of punctuation really hinders my ability to comprehend your post. This repository is actually for the website that serves datafiles, not datafiles themselves.

I'm not entirely sure what repository is your issue directed at, I can only suggest you to choose the one you actually talk about. I can guess you meant https://github.com/BSData/wh40k-heralds-of-ruin-killteam - if so, please open a new issue there. :)

**Comment by don124** [comment]
Warhammer 40.000 8th edition V40
Imperium - Deathwatch V19
Troops
Deathwatch Kill Team

Can you please insert into this catalogue all types of primaris space marines with the following names 

Intercessor marine
Agressor marine
Reiver marine
Inceptor marine
Hellblaster marine 

With all there weapon options and as a single marine and not a squad so people have the choice of being able to create the very own primaris kill team and not just a normal marine kill team as primaris marines have been out for quite some time now this would be much appreciated

**Comment by tekton** [comment]
@don124 I'm not seeing anything in the FAQ of Imperium 1 Index that would allow that to be a valid formation/squad of Deathwatch Kill Team.

There will be NEW rules for the upcoming game Kill Team that was announced that we don't know what they will be, but that is separate from the core 40k game and rules.
