### ISSUE TITLE
Missing Repos on battlescribedata.appspot.com

### ISSUE THREAD

**Issue by XWingDrLucky** [BSData/bsdata#195]
When I pull up battlescribedata.appspot.com only about half of the repos appear when the page loads.  Of the repos I maintain, I notice that the repo for Star Wars: X-Wing appears but Star Wars: Legion and Star Wars: Armada don't show up. The pages are still here on github - they just aren't showing up on the battlescribedata.appspot.com front page.

**Comment by MasterSlowPoke** [comment]
Even the normal 40k repo is gone.

**Comment by amis92** [comment]
All except Armada are there now, so it was a typical after-release hiccup.

Armada might have an actual problem though. @Jonskichov can you check for a reason?

**Comment by XWingDrLucky** [comment]
Everything seems to be in order now.  I'm not sure what happened or why it is working again but since there doesn't seem to be an active, identifiable issue, I'll close this.
