### ISSUE TITLE
No datafiles downloadable

### ISSUE THREAD

**Issue by Hellgore1974** [BSData/bsdata#198]
Can't get any Datafiles for android. "There was an error getting the data files. The site may be overloaded right now. Please try again later."  Is showing since saturday now when I follow the repository-link. I have the latest BS version .21.283
Because I normally delete old data when updating I'm now left with no data at all for my army lists :(
Anybody able to help?

**Comment by superallumette** [comment]
Hello,
Same here, there is an HTTP 500 Error from the server.

**Comment by amis92** [comment]
I've reset the machine, should work again.
