### ISSUE TITLE
New repo: X-wing 2.0

### ISSUE THREAD

**Issue by Starkman9000** [BSData/bsdata#206]
I would like to add a new repo for FFGs Star Wars X-wing Second Edition. I have the core set converted already and will be working on the rest throughout the week.

Regards.

**Comment by amis92** [comment]
Please discuss it with the x-wing repo maintainer in an issue opened in that repository. We do not practice "new repo for new edition" with very few exceptions, like the 8th ed of 40k.

**Comment by amis92** [comment]
That's the repo: https://github.com/BSData/swxwing

**Comment by Starkman9000** [comment]
Just a question, but what would qualify a repo for an exception? I've opened a ticket on the x-wing repo, but feel like there won't be any plans to update due to major format change the new edition has.

**Comment by amis92** [comment]
To answer shortly, there are no specific indicators or conditions for an exception. That one time it was done for 8th was a long discussion, and it was a result of many, many changes we were doing, including reorganization of the team structure, the organization structure, repo access rights, complete rewrite, a very strict and announced cutoff of the 8th (index thing, all new rules), and so on. There are others, like Firestorm V2 I believe, but that's a legacy issue never consulted with me, and Necromunda, which is another misunderstanding and also a little bit of naming chaos GW introduced with Gang War and Underhive.

Paging https://github.com/BSData/swxwing/issues/23 for reference
