### ISSUE TITLE
BattleScribe Android app via F-Droid possible?

### ISSUE THREAD

**Issue by r4dh4l** [BSData/bsdata#216]
Hi,

I couldn't find the repo for for https://play.google.com/store/apps/details?id=net.battlescribe.mobile.rostereditor so sorry if this request is in the wrong category: Would it be possible to provide the Android app via https://search.f-droid.org/ as well?

**Comment by amis92** [comment]
Please open this issue in https://github.com/BattleScribe/Release :)

**Comment by r4dh4l** [comment]
https://github.com/BattleScribe/Release/issues/31 - done, thx! :)
