### ISSUE TITLE
Question regarding Joining

### ISSUE THREAD

**Issue by Drizzt-IT** [BSData/bsdata#219]
Hi,
I would like to add the Data for Wild West Exodus and Dropzone Commander.
I opened an Issue in each for joining. But there has no one been active for a very long time.
So I'm not sure how long I should wait for a response?

How long does it usually take?

**Comment by amis92** [comment]
Hi, sorry, I've been busy, then forgot, then forgot again and now I've sent the invites :)

**Comment by Drizzt-IT** [comment]
Thx!
