### ISSUE TITLE
No Mountable File Systems

### ISSUE THREAD

**Issue by vderkara** [BSData/bsdata#223]
Hey trying to download and install latest update on my macbook. Its giving me a "no mountable file system" when I try to open the .dmg. Anyone come across this? any solutions?

I've tried:
disk repair the HD.
downloading from a different browser.
mounting from Terminal.
Rebooting.

nothing works.
Other .dmgs are able to mount. Makes me wonder if downloaded file is corrupted.

**Comment by amis92** [comment]
Please raise it on https://github.com/BattleScribe/Release

This repo is only for datafile-serving webapp/website.
