### ISSUE TITLE
Errors: NameResolutionFailure

### ISSUE THREAD

**Issue by Lionaus** [BSData/bsdata#224]
When I go to my data repo (recently uninstalled and reinstalled the app after not using it for 2 years to try and fix this error) it comes up with the above error message. The same message comes up when I try to load any repo data. 

Any ideas how to fix this? Looks like it’s an error that’s gone on for a while but never had a clear “this is how to fix it” answer from what I can see on reddit etc

**Comment by amis92** [comment]
Please raise it on https://github.com/BattleScribe/Release

This repo is only for datafile-serving webapp/website.
