### ISSUE TITLE
About localization fo wh40k

### ISSUE THREAD

**Issue by zhangxianzhong** [BSData/bsdata#225]
I forked BSData/wh40k and localized it to Chinese And I want to keep updating it. Can I post it to battlescribedata.appspot.com,This is my project https://github.com/zhangxianzhong/40K-Chinese-Localization

**Comment by amis92** [comment]
This is already answered in https://github.com/BSData/catalogue-development/issues/15

I'm sorry, but currently the answer is no. Please follow the issue linked above. It's still on our radar. :)
