### ISSUE TITLE
Repo Vanguard gone ????

### ISSUE THREAD

**Issue by BitPsycho** [BSData/bsdata#227]
Hi,

The repository 'Kings of War - Vanguard' has disappeared from appspot ?  The latest release (8) was published 16 days ago and was there just fine ...  since then I didn't change anything.

http://battlescribedata.appspot.com/#/repo/kings-of-war-vanguard 

What happened ?

Thanks

**Comment by amis92** [comment]
That's the repo for datasite issues

**Comment by amis92** [comment]
Duplicate of #208
