### ISSUE TITLE
Rename The Walking Dead: March to War to The Walking Dead: Call to Arms

### ISSUE THREAD

**Issue by mugginns** [BSData/bsdata#229]
Hi, can you please rename this repository:

https://github.com/BSData/the-walking-dead-march-to-war

They changed the name of the game during beta and its now 'The Walking Dead: Call to Arms". Thanks

**Comment by amis92** [comment]
I can rename it, sure. Will the people know to re-subscribe? What I mean is, the BattleScribe saves the address (url part) for updates. If I change the URL, they won't get updates until they re-subscribe to the "new" repo URL.

**Comment by mugginns** [comment]
Yes, they will. Thanks

**Comment by amis92** [comment]
Rename commencing.

**Comment by amis92** [comment]
Done. New repo url: https://github.com/BSData/the-walking-dead-call-to-arms
