### ISSUE TITLE
Release push failed

### ISSUE THREAD

**Issue by Mayegelt** [BSData/bsdata#252]
Hello, not 100% sure if this is the place to put it or not, however...
The latest Horus Heresy push was put for release 3 days ago, and when it went live to appspot it seems to have be lacking the files it should have included.
Tried again this morning 29th and once again same thing.
Not sure what is wrong. But kept checking to see if appspot was updating, and it seems to be working with things like the 40K releases, but is now not functioning with the HH ones.

https://github.com/BSData/horus-heresy

**Comment by amis92** [comment]
It's generally speaking another example #208 in action. See the issue for details. TLDR: wontfix. :(
