### ISSUE TITLE
Access for the-9th-age-essence-of-war

### ISSUE THREAD

**Issue by rzmoz** [BSData/bsdata#254]
Hello, I'm sorry but I'm not sure where to ask this question

Please grant DarkSkyT9A contributor access to https://github.com/BSData/the-9th-age-essence-of-war.

Access so he can contribute directly to the repo / approve PRs etc.

He is part of the T9A team and is already working on https://github.com/BSData/The-9th-Age

Please let me know if there's anything else you need.

**Comment by DrTobogganMD** [comment]
Hi Rzmoz, is that a git username?

**Comment by DrTobogganMD** [comment]
Hello, @rzmoz. Please have Darksky accept the invitation in the email or on the [webpage][invitation]. Welcome aboard to him!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

[invitation]: https://github.com/BSData/the-9th-age-essence-of-war/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
