### ISSUE TITLE
Removed from organisation, repository archived

### ISSUE THREAD

**Issue by MattunR** [BSData/bsdata#256]
Hi guys,

I made and maintained the Maelstrom's Edge repository. Probably due to inactivity, in 2018 I received mails saying "The Data Authors - Maelstrom's Edge team on the BSData organization has been deleted." and "You’ve been removed from the BSData organization." Also, github.com/BSData/maelstroms-edge has been archived. We're now getting to v2 of this game and would like to update these files again. So, my request is: any way back in? :)

Cheers,

Marten

**Comment by amis92** [comment]
Hi, the repository has been unarchived. https://github.com/BSData/maelstroms-edge

There was already a request for it from an account named `MaelstromsEdge`. We can add you back in, please open a join-request issue over there.
