### ISSUE TITLE
Show Revision numbers as part of internal file name?

### ISSUE THREAD

**Issue by StealthKnightSteg** [BSData/bsdata#28]
As of  how I do it now is give a version number in the internal filename:
e.g. Beastmen - Army Book (2013.4) - V8.7.4.
leaving the last number open as the file then mentions the revision number.

Now this might be something to be solved with Battlescribe itself, but it's an issue I see popping up here due to our naming convention.

**Comment by Jonskichov** [comment]
The data site shows file author and revisions number.
