### ISSUE TITLE
Making Issues visible on the page for end users?

### ISSUE THREAD

**Issue by StealthKnightSteg** [BSData/bsdata#32]
Is this possible as it will give our end users insight in which bugs are open and which are closed and for what reason.

**Comment by Jonskichov** [comment]
I like the idea but... (there's always a but...)

1) I won't have time to do this (or any other major improvements to the data site) and we don't appear to have anyone else taking up the reigns on it. Not that I/we have tried very hard to find anyone ;)

2) This would mean more hits on GitHub and we are tending to bump into their limits as it is just downloading / refreshing the data cache from the repos...
