### ISSUE TITLE
Firestorm Planetfall Host Request

### ISSUE THREAD

**Issue by stevecodeguy** [BSData/bsdata#55]
Hello all,

I have begun files for Firestorm Planetfall. I'd like to host them on the http://battlescribedata.appspot.com/#/repos website. How would I go about doing this?

Thanks,

Steve.

**Comment by amis92** [comment]
Yeah, sure. I'm away skiing in mountains and had a break from internet, so sorry for the delay. To "call" someone directly, write ```@amis92``` for example - that'd notify me directly.

Also, such system-specific things are best asked in issues in appropriate repo. https://github.com/BSData/firestorm-planetfall/issues
Everybody can open an issue.
