### ISSUE TITLE
Heralds of Ruin

### ISSUE THREAD

**Issue by dogrizz** [BSData/bsdata#58]
Hi
After few years of absence of 40K I recently dabbled in Heralds of Ruin Kill Team.
(http://heralds-of-ruin.blogspot.com/p/kill-team-rules.html)
Is there a possibility to alter 40k data files for this?
Some of the armies already have the possibiity to choose any squad members numbers (from 1 and in eldars you can also choose exarch only) and that would be already cool.
Having the upgrades would be icing on the cake.
Or that would require separate data files to do it "gud and propa"?

**Comment by khambatta** [comment]
@new-neon has been working on files for that; drop him a line.
The repo so far is here:
https://github.com/BSData/wh40k-heralds-of-ruin-killteam
