### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by ChrisJensenDK** [BSData/bsdata#61]
I'm hoping to start a new repo for Games Workshop's Hobbit SBG

**Comment by amis92** [comment]
Oooh hey there, sorry, I was away from PC for awhile. Welcome to the group! What would you like Hobbit to be called? `hobbit` is enough, or `hobbit-sbg` would be better? I think `hobbit`. When we decide, I'll create a new repo for you and give you tip here.

You can search for other such (closed) issues here to read some tips for filling new repos. Any questions I'll gladly answer.

**Comment by ChrisJensenDK** [comment]
No worries :+1:
I was thinking Hobbit SBG is best, however I have actually taught myself the functionality of BattleScribe and have already started creating the repo.
What would be best - that the repo I'm working on is added on here, or that I start over on a new repo that you create? I don't mind starting over at all, so whatever you think is best, is what we'll do :)

**Comment by amis92** [comment]
Yeah creating new repo is probably easier than transferring from your account (repo has to be under organisation ownership). Of course you can copy files over, that's no problem. Just remember to follow guidelines from our Wiki here (ie. save catalogues "save as" and choose ".cat" not ".catz" etc.).

So, here we go https://github.com/BSData/hobbit. Accept the invitation (sent by email 3 days ago or on our organisation homepage http://github.com/BSData )
