### ISSUE TITLE
Incorrect points in CSM selections

### ISSUE THREAD

**Issue by mickyster** [BSData/bsdata#62]
So the amount of points is out for CSM.  Base 13 points including a bolt gun nd pistol + 2 points to add a CCW.

Or exchange the boltgun for CCW.  

The amount of points for each option adds 1 point for either a CCW or Bolt Gun or 3 for both.  Should be zero for either or 2 extra for both.  Says that on selection screen but using the wrong amounts above in totals.  

Sorry if this is wrong spot.

Thanks

**Comment by mickyster** [comment]
Seems to be fixed now thanks

**Comment by amis92** [comment]
@mickyster Thanks, but for future, please report system-specific bug reports on appropriate repo. In that case, it'd be https://github.com/BSData/wh40k/issues

Cheers!
