### ISSUE TITLE
Adding New Game files to Appspot

### ISSUE THREAD

**Issue by Vescarea** [BSData/bsdata#65]
Hi, i have a WIP game file for the appspot as it doesn't exist. It's for the Judge Dredd Miniatures game. i created a repository and the clone folder.

**Comment by amis92** [comment]
Hi. Thank you. Here's your link.
https://github.com/BSData/judge-dredd
I suggest you now fork this one and work on the fork, making pull requests as needed. Any further questions? Don't hold it, just ask me! :)

**Comment by Vescarea** [comment]
Awesome Thank you :) im finishing off a section so will get it up soon. im still bit new to how this all works but ill get there.

**Comment by Vescarea** [comment]
Hey, ive got a new update for the repo ive uploaded it to my current repro whats the next step?

**Comment by amis92** [comment]
Hey there. As I've mentioned, you should make a pull request from your fork https://github.com/Vescarea/judge-dredd
If you have further questions with pull requests, GitHub's help contains appropriate tutorials. https://help.github.com/articles/fork-a-repo/

**Comment by amis92** [comment]
After reviewing your commits, I'll suggest you remove files such as change summary. Repo should only contain .cat and .gst files. Release notes (and change log) should be included in Release information on GitHub, for example this is the first Judge release: https://github.com/BSData/judge-dredd/releases/tag/v1.0
