### ISSUE TITLE
Developer access to SW-Armada

### ISSUE THREAD

**Issue by BlueSeven** [BSData/bsdata#67]
Hi, Could I have developer access to the Star-Wars-Armada repository please?
I've been helping BrianisBlack with it on the FFG forums previously.
Thanks.

**Comment by amis92** [comment]
Please open issue in appropriate repo as per https://github.com/BSData/bsdata/wiki#getting-started

I'm sorry to sound a little "bureaucratic", but I have to manage this whole organisation by myself lately, so I need to keep it all in line.
