### ISSUE TITLE
Chaos dwarfs 8th. ed.

### ISSUE THREAD

**Issue by daravan** [BSData/bsdata#69]
Do you have any data?

**Comment by daravan** [comment]
For bs

**Comment by amis92** [comment]
I can only guess you're talking about WFB? If so, please ask in appropriate repo. We here don't manage data files. This repo is for website.

WFB: https://github.com/BSData/whfb

**Comment by amis92** [comment]
Oh, and also after quick glance, thay do have chaos dwarfs. Have you used http://battlescribedata.appspot.com/#/repos ? You can download data there.
