### ISSUE TITLE
Game file for relic knights

### ISSUE THREAD

**Issue by questing-knight** [BSData/bsdata#70]
I completed a game repository for Relic Knights by Soda Pop Miniatures.  It has been posted on Soda Pop's forums for some time and no major issues reported so it seems ready to be hosted on a known battlescribe repository site.

**Comment by amis92** [comment]
Great to hear so. Let me do the magic... her is the repo: https://github.com/BSData/relic-knights

Would you like to become BSData member or do you prefer making pull requests?
https://github.com/BSData/bsdata/wiki/Membership-Guidelines#to-be-a-member-or-not-to-be

And also for completeness: https://github.com/BSData/bsdata/wiki/Developer-Guide

**Comment by questing-knight** [comment]
Thanks Amadeusz!

I think I will stick with pull requests.  Thanks again!

On Thu, May 21, 2015 at 2:31 PM, Amadeusz Sadowski <notifications@github.com

**Comment by amis92** [comment]
@questing-knight please respond within 14 days with some message if you're still interested in this project. Otherwise I'll delete the repository, as it stays empty.

**Comment by efalsken** [comment]
I'll take ownership. I've got a data file set for this game already started.

**Comment by amis92** [comment]
Great, you already have push access. Closing.
