### ISSUE TITLE
9th Age files

### ISSUE THREAD

**Issue by JimmyMalmer** [BSData/bsdata#72]
Hello, I'm the lead developer of the Battlescribe files for the community project Warhammer 9th age. The files are not quite finished, but I thought I'd request possibility to upload them a bit ahead of time.

//Jimmy

**Comment by amis92** [comment]
Allright, I do think there is a possibility for that. :)

**Comment by JimmyMalmer** [comment]
Right, so how do we do this? Is it possible to push it directly to appspot, or do we have to send you new versions?

**Comment by amis92** [comment]
Okay, so @Toreador13 created the repo, I've initialized it, now I've sent you an invitation to the Data Authors team, please accept it and read on: https://github.com/BSData/bsdata/wiki/Developer-Guide 

I'll close this issue, but if anything else comes up, just mention me (`@amis92`) in some comment here or there.
