### ISSUE TITLE
Epic Armageddon repo

### ISSUE THREAD

**Issue by afraeve** [BSData/bsdata#73]
I have a good-sized set of files for Epic Armageddon if you'd like to set up a repo for them.

**Comment by afraeve** [comment]
The work can be found here if you want to check them out in the meantime: 
https://github.com/afraeve/Epic-Armageddon

**Comment by amis92** [comment]
Hey, @afraeve sorry for delay. If you want a repo, would you like to join the team and look over it? We lack the people to take care of files, so... you know. I mean, I'll create a new repo now and send you an invitation to Games Workshop games team, and then you'll take care of the rest. Deal?

**Comment by amis92** [comment]
There you go: https://github.com/BSData/wh40k-epic-armageddon

**Comment by afraeve** [comment]
Neat-o, thanks @amis92.
