### ISSUE TITLE
New Game files 

### ISSUE THREAD

**Issue by Vescarea** [BSData/bsdata#74]
Hi i have a new game system to add on the appspot the link is here https://github.com/Vescarea/Frostgrave

The new game is called Frostgrave

**Comment by amis92** [comment]
Oooh sorry I've lost this issue somehow. Would you mind taking care of the repo? I don't have time to manage any more repositories. So, I'll invite you to the team, and you'll manage Judge Dredd and Frostgrave, deal? :)

**Comment by amis92** [comment]
@Vescarea here you go https://github.com/BSData/frostgrave

**Comment by Vescarea** [comment]
Yh sure thing :) will be glad to help out and thanks again.


Sent from Samsung Mobile on O2

-------- Original message --------
