### ISSUE TITLE
Release not pushing latest version

### ISSUE THREAD

**Issue by BrianisBlack** [BSData/bsdata#76]
The last two releases I did for star-wars-armada have not gotten pushed to (at least) the battlescribe client I've got on my iPhone. The files are definitely committed to the github server on the only branch there, so I'm not sure why they wouldn't be included in the releases I've done recently.

The third from last release I did on 9/24 did go through with no issue, so I'm not sure what changed since then. Any help or directions to look in to start would be appreciated!

Thanks,
Brian

**Comment by BrianisBlack** [comment]
... And suddenly everything's gone through.  Dunno what changed but my particular issue seems to be resolved.  I'm a bit confused why it took so long for the update to push though.

**Comment by amis92** [comment]
Well the app pulls the updates once per X hours, where I have no idea what X is. :) That's just how it works.
