### ISSUE TITLE
Halo Fleet Battles

### ISSUE THREAD

**Issue by KealL** [BSData/bsdata#77]
Hi I'd like to contribute the basic setup for Halo Fleet Battles that I have put together. But don't know how to add it?

**Comment by amis92** [comment]
I've invited you (you need to accept it, it's on your email and on https://github.com/BSData) to organization and created the repository: https://github.com/BSData/halo-fleet-battles

Now you need to provide the files. Please read through wiki: https://github.com/BSData/bsdata/wiki/Developer-Guide and other pages.

Good luck and if there's any problem, just mention me like that: `@amis92` in any issue comment.
