### ISSUE TITLE
Halo Fleet Battles

### ISSUE THREAD

**Issue by KealL** [BSData/bsdata#78]
Hi

Am trying to sync my data to the repository but it says I don't have permission.

![image](https://cloud.githubusercontent.com/assets/14986801/10347800/8d97a3ba-6d2d-11e5-82f3-38f30ad429ab.png)

**Comment by KealL** [comment]
@amis92

**Comment by amis92** [comment]
Uh, sorry. Fixed now. GitHub introduced new permission system and I got caught off guard.
