### ISSUE TITLE
Gates of Antares Files

### ISSUE THREAD

**Issue by mugginns** [BSData/bsdata#80]
Hello,

I am working on Gates of Antares roster files - how would I get them uploaded? They are not done yet, but I'd like to begin testing with folks. Thanks

**Comment by amis92** [comment]
Testing is a part of our job, so let's just go ahead and publish the repository. Here you go: https://github.com/BSData/gates-of-antares

I've initialized it, now I've sent you an invitation to the Data Authors team, please accept it and read on: https://github.com/BSData/bsdata/wiki/Developer-Guide 

I'll close this issue, but if anything else comes up, just mention me ( @amis92 ) in some comment here or there.
