### ISSUE TITLE
9th Age access

### ISSUE THREAD

**Issue by bombastian2000** [BSData/bsdata#83]
Hi, I'm part of the 9th age work force and would like access to the repo.

**Comment by JimmyMalmer** [comment]
Confirming he is legit.

**Comment by amis92** [comment]
@JimmyMalmer I'm testing new privilege system. I've created @BSData/data-authors-the-9th-age and promoted you to team maintainer. Can you add @bombastian2000 by yourself? Team page: https://github.com/orgs/BSData/teams/data-authors-the-9th-age

**Comment by JimmyMalmer** [comment]
"Only organization owners can Send invitations"

**Comment by amis92** [comment]
Right. So it is that I have to add him to organization, and only then can you add him to the team. Okay, I've invited him.
