### ISSUE TITLE
Farsight enclaves not there

### ISSUE THREAD

**Issue by cookiesnm1lk** [BSData/bsdata#88]
So....the entire Farsight Enclaves supplement codex for the Tau Empire seems to be missing from my data files. i KNOW these EXIST because on my desktop they are there. and on my laptop they are not. what do?

**Comment by cookiesnm1lk** [comment]
ugh. nvm. i figured it out. by the way, that's bad organization.....

**Comment by amis92** [comment]
wrong repo, yeah.
