### ISSUE TITLE
support on game system editer

### ISSUE THREAD

**Issue by Rooee4** [BSData/bsdata#89]
I'm trying to finish the pale courts out of ia the doom of mymeara but there's no Support id on the system game editor on battlescribe how can I ad one.

**Comment by Jonskichov** [comment]
Wrong place for this I'm afraid.

Try Reddit (https://www.reddit.com/r/BattleScribe) for questions on how to use the apps, or ask for advice from the 40k data authors (https://github.com/BSData/wh40k)
