### ISSUE TITLE
Repositories Not Available (500 Error)

### ISSUE THREAD

**Issue by JCRobertson** [BSData/bsdata#90]
The repositories are not able to be fetched by Battlescribe and are not displayed on the appspot page. There is a 500 error when trying to access http://battlescribedata.appspot.com/repos that is logged in the browser js console. In addition, the angular object m.repos is empty and is not being repeated by ng-repeat in it's ul element.

**Comment by amis92** [comment]
Site now works. It could be data limit overrun again.
