### ISSUE TITLE
Ghostkeel Support system upgrade

### ISSUE THREAD

**Issue by warshepard** [BSData/bsdata#91]
Xv95 Ghostkeel battlesuits can take up to two items form the support systems. Vectored retro-thrusters are not added to this list on battlescribe. The only restriction for vectored-retro-thrusters are: " models with xv-88 cannot be equipped with vectored retro-thrusters".

**Comment by amis92** [comment]
@warshepard that's a wrong repo. Please open this issue again here: https://github.com/BSData/wh40k
