### ISSUE TITLE
BattleScribe 1.16.00 ALPHA

### ISSUE THREAD

**Issue by Jonskichov** [BSData/bsdata#92]
@BSData

**This issue has been moved to the BattleScribe GitHub organisation: https://github.com/BattleScribe/Alphas/issues/1**

**Comment by Thairne** [comment]
For consistency and easy access, listing my first findings here too:
-  Unable to load old (Dark Angels) lists. Likely to be caused by the next problem.
-  Unable to create new (Dark Angels or Skitarii) lists. After selecting game system, points limit and forces, a click on ok does nothing. Don't know where you keep the stack traces, therefore unable to provide the (probable) exception. Works with Cult Mechanicus, so probably a cause in the data files.
 -  Creating a valid Cult Mechanicus CAD and trying to save it pops up an error: "Roster must have a battlescribe version" and multitudes of "Profile must have a type"

**Comment by Jonskichov** [comment]
@Thairne Looking into this stuff now. Will try to get an update out later tonight.

**Comment by cartag** [comment]
Repeat condition to modifiers will not correct listing on left, the "... of <NO CHILD> should be removed. 

Example:
Repeat 1 times for every 1000pts limit in roster.

![image](https://cloud.githubusercontent.com/assets/4388344/12460296/58761b7c-bf70-11e5-8c68-fea4c14246a7.png)

**Comment by Jonskichov** [comment]
**Build 10**
**This update fixes some XML issues so you will have to revert to 1.15.x data and re-convert it**. I'd like to promise this will be the last time, but I won't...

@Thairne  I'm working through the main issues with DA not loading. Turned out to be a bit more in depth than I hoped. So I'm just pushing out this build for now to get rid of some of the other bits. Also I need to double check your other questions. Stay tuned.

**Changes**
- Fixed issues validating points limit conditions/repeats (@cartag)
- Fixed incorrect XSL for points limit fields in conditions/repeats
- Fixed typo in XSL that caused problems with SelectionEntryGroups
- Fixed crash removing shared entries (@Thairne)
- Fixed "Roster must have a BattleScribe version" error (@Thairne)

**Comment by cartag** [comment]
After I had three bugs I'd found, I decided to do them separate. If you prefer them all in the same thread next time, I can do that too. 

Is there any additional information I'm not currently giving that would be helpful in tracking down bugs?

**Comment by Jonskichov** [comment]
@cartag Actually yeah, separate issues is good. I will use this issue for release announcements and for general feedback.

**Comment by cartag** [comment]
@Jonskichov figured that was the case :) I'll let you know if I break anything else.

**Comment by Jonskichov** [comment]
This whole alpha business is new, so I'll probably figure things out as I go. Mostly I just want to make sure you guys are cool with the direction of things!

That said, so far there's been some _really_ dumb issues... Perhaps it should have been left in the oven for another week or so...

**Comment by cartag** [comment]
Totally cool with how it's progressing. And look at it this way instead. Rather than leaving it in the over for another week or two, by airing it out a bit early you get feedback quicker, thus shortening the time you'll need in the future for it.

**Comment by cartag** [comment]
Also, I hate to come across like I'm just tearing apart your baby. I love BS, so much that I've bought it on both my phone and PC. Please don't think I'm upset or anything with posting all the bug reports, I just want this to be the best program it can be :)

**Comment by amis92** [comment]
Yeah,  I agree with @cartag, alpha testing is really good. You may feel some of those dumbies are not something you'd like to publish. But that's really positive: we get to see you're alive, and the work is damn dynamically going forward.

Cheers!

**Comment by Jonskichov** [comment]
Good stuff :)

You're not "tearing it apart" - I _want_ to hear about bugs! :)

This is a major update, so there's likely to be issues. I want to try and make sure there's no major show-stoppers when release day comes around...

**Comment by Jonskichov** [comment]
@cartag @Thairne @amis92 

I've gone whole-hog and created a BattleScribe organisation here on GitHub. As @amis92 suggested, this Alpha business needs it's own repo, and I suppose it's probably best to separate it out from the BSData organization.

I was going to copy/paste your issues over myself, but I guess it would be better for you to do it yourselves for the sake of notifications and the like.

The main Alpha issue is here: https://github.com/BattleScribe/Alphas/issues/1
And the issue tracker is here: https://github.com/BattleScribe/Alphas/issues
