### ISSUE TITLE
Maelstrom's Edge hosting request

### ISSUE THREAD

**Issue by MattunR** [BSData/bsdata#93]
Hey guys,

The Battlescribe repositories page directed me here, so here I am :). I'm not familiar with Github, but here's what I've come for:

I created data files for a recently released game, Maelstrom's Edge (maelstromsedge.com  if you're interested). The company behind the game is happy to let me make my data files available to the public, so that's what I'd like to do! So basically, my question is what I need to do to get my repository on to this page?

Thanks!

**Comment by Jonskichov** [comment]
Er not sure who you need to talk to, but @amis92 might :)

**Comment by MattunR** [comment]
Thanks Jon, will try him :)

**Comment by amis92** [comment]
Hi there. If you have the files, you'll need to populate the repo I've created for you: https://github.com/BSData/maelstroms-edge

To do that, please accept the invitation I've sent you (in email, or on https://github.com/BSData ). Then you'll gain push access and after cloning the repo locally, please add the files (in .cat and .gst format, not .catz or .gstz), commit and sync.

Any further questions, you can post here (even if issue is closed), and mention me by `@amis92` (no reason for mailing ;)

Cheers!

**Comment by MattunR** [comment]
@amis92 

Awesome! Whole new world for me, but I think I got all my stuff where it needs to be. Thanks! Will the repository magically appear on battlescribedata.appspot.com now that I released the files, or do I need to take additional steps, as it's a new game system?

**Comment by amis92** [comment]
It's already here http://battlescribedata.appspot.com/#/repo/maelstroms-edge (it takes up to few hours to refresh for every release)
Good job!
