### ISSUE TITLE
Roster Editor - Starting New Roster after Roster already loaded/started

### ISSUE THREAD

**Issue by cartag** [BSData/bsdata#94]
__Build 10 Bug report__

__Roster Editor__
* After a roster is active, new or existing, unable to load a new Roster without cancelling after hitting OK. 
 1. Start new roster, selecting force, detachment, etc. 
 2. Click New Roster button, don't save, select new force/detachment options
 3. Used Imperial Knight 2014, only 15kb file.
 4 Press OK on New Roster screen
 * Wait 30 sec, no difference seen in BS.
 * Press Cancel, old roster disappears, new roster appears.

**Comment by Jonskichov** [comment]
On the list, thanks for the feedback.

**Comment by Jonskichov** [comment]
Moved here: https://github.com/BattleScribe/Alphas/issues/10
