### ISSUE TITLE
Data Editor - Condition, Query, Selections

### ISSUE THREAD

**Issue by cartag** [BSData/bsdata#96]
__Build 10 Bug report__
__Data Editor__
* For Repeat conditions, has a listing of all force options there, not selections from the army list itself like it should.
![image](https://cloud.githubusercontent.com/assets/4388344/12500285/e56d42f4-c06e-11e5-8f6c-5a35e01f733a.png)

**Comment by Jonskichov** [comment]
Moved: https://github.com/BattleScribe/Alphas/issues/11
