### ISSUE TITLE
Data Editor - Condition, Filter By, Selections

### ISSUE THREAD

**Issue by cartag** [BSData/bsdata#97]
__Build 10 Bug report__
__Data Editor__
* Under Conditions, for Selections, it seems to order things strangely, not alphabetically. Does not appear to sort by ID, but does group by type (Elite, Troop, Heavy Support, etc)
![image](https://cloud.githubusercontent.com/assets/4388344/12500095/275e76d0-c06d-11e5-8759-b80956169cb9.png)

**Comment by Jonskichov** [comment]
It _should_ sort by the order it finds stuff in the file, so that it keeps the tree structure of the file. Is this the case?

Some alphabetical sorting should probably be done though.

**Comment by cartag** [comment]
Tree structure of the file is in alphabetical order. From what I can tell, it's sorting things out that are in Selection Entries, sorted by what unit type they are.

**Comment by Jonskichov** [comment]
Moved: https://github.com/BattleScribe/Alphas/issues/12
